init:
	# --< Landing Zone >-----------------------------------
	rm -rf landing
	mkdir landing
	mkdir landing/pqrs
	mkdir landing/pqrs/leetter
	mkdir landing/pqrs/web
	
	# --< Raw Zone >---------------------------------------
	rm -rf raw
	mkdir raw
	mkdir raw/pqrs
	mkdir raw/pqrs/leetter
	mkdir raw/pqrs/web


	
	